/**
 * The corridors the signalling blueprint can draw.
 *
 * This file is the single source of truth for corridor shape. It used to be a
 * bare list of CRS codes, with everything else — station names, which stations
 * are junctions, which branches leave where, and what each branch page is
 * called — hardcoded separately inside the renderer and the branch route. Those
 * four copies drifted (14 branch links against 15 branch pages), so they now
 * all read from here instead.
 *
 * Station order is the drawing order: index 0 is the top of the diagram.
 * Real distance between stations comes from station_track_model_position at
 * render time, not from this file — see the renderer's mileage handling.
 */

export type SignallingCorridorId = string;

export interface CorridorStation {
  crs: string;
  /** Display name. Validated against the `station` table by the corridor test. */
  name: string;
  /** Draws a heavier tick and a full name rather than just the CRS. */
  junction?: boolean;
}

export interface CorridorBranch {
  /** Slug, and the /signalling/<id> route it links to. */
  id: SignallingCorridorId;
  /** The station on this corridor where the branch leaves. */
  atCrs: string;
  label: string;
  /** Which side of the diagram the spur hangs off. */
  side: "up" | "down";
}

export interface SignallingCorridor {
  id: SignallingCorridorId;
  title: string;
  shortTitle: string;
  stations: CorridorStation[];
  branches: CorridorBranch[];
  /** Set on branches: the corridor they leave from, for the "back to" link. */
  parentId?: SignallingCorridorId;
  /** The station on the parent corridor this one leaves from. */
  parentAtCrs?: string;
}

/**
 * Track Model's TRACK_ID → the name signallers actually use.
 *
 * NWR_TrackCentreLines has ASSET_ID, ELR, TRACK_ID, START, END and nothing
 * else — there is no field anywhere in the extract carrying a human name for a
 * running line. Track *count* and *extent* are therefore fully derived from the
 * data (see `etl track-sections`), but the names have to come from somewhere,
 * and this is that somewhere.
 *
 * Deliberately hand-written rather than inferred from the ID's shape: the
 * numbering looks systematic (1xxx down, 2xxx up, x100 fast, x200 slow) but a
 * confidently wrong label on a signalling diagram is worse than no label, so
 * anything not listed here falls back to `Line <id>` via trackRoleName().
 */
const TRACK_ROLE_NAMES: Record<string, string> = {
  "1100": "Down Fast",
  "2100": "Up Fast",
  "1200": "Down Slow",
  "2200": "Up Slow",
  "1300": "Down Local",
  "2300": "Up Local",
};

export function trackRoleName(trackId: string): string {
  return TRACK_ROLE_NAMES[trackId] ?? `Line ${trackId}`;
}

function s(crs: string, name: string, junction?: boolean): CorridorStation {
  return junction ? { crs, name, junction: true } : { crs, name };
}

/**
 * Every corridor, trunk first.
 *
 * Station names and CRS codes are not hand-typed: they were generated by
 * looking each station up by name in the GTFS stops file (data/gtfs), which is
 * the same timetable data the routing engine runs on. Writing them from memory
 * produced a 32% error rate on a first pass — including two stations whose
 * codes were transposed — so the corridor test re-checks every code against the
 * `station` table to keep it that way.
 */
const CORRIDORS: SignallingCorridor[] = [
  {
    id: "swml",
    title: "South West Main Line",
    shortTitle: "SWML",
    stations: [
      s("WAT", "London Waterloo", true),
      s("VXH", "Vauxhall"),
      s("QRB", "Queenstown Road (Battersea)"),
      s("CLJ", "Clapham Junction", true),
      s("EAD", "Earlsfield"),
      s("WIM", "Wimbledon", true),
      s("RAY", "Raynes Park", true),
      s("NEM", "New Malden", true),
      s("BRS", "Berrylands"),
      s("SUR", "Surbiton", true),
      s("ESH", "Esher"),
      s("HER", "Hersham"),
      s("WAL", "Walton-on-Thames"),
      s("WYB", "Weybridge", true),
      s("BFN", "Byfleet & New Haw"),
      s("WBY", "West Byfleet"),
      s("WOK", "Woking", true),
      s("BKO", "Brookwood", true),
      s("FNB", "Farnborough (Main)"),
      s("FLE", "Fleet"),
      s("WNF", "Winchfield"),
      s("HOK", "Hook"),
      s("BSK", "Basingstoke", true),
      s("MIC", "Micheldever"),
      s("WIN", "Winchester"),
      s("SHW", "Shawford"),
      s("ESL", "Eastleigh", true),
      s("SOA", "Southampton Airport Parkway"),
      s("SOU", "Southampton Central", true),
      s("MBK", "Millbrook (Hants)"),
      s("RDB", "Redbridge", true),
      s("TTN", "Totton"),
      s("ANF", "Ashurst New Forest"),
      s("BEU", "Beaulieu Road"),
      s("BCU", "Brockenhurst", true),
      s("SWY", "Sway"),
      s("NWM", "New Milton"),
      s("HNA", "Hinton Admiral"),
      s("CHR", "Christchurch"),
      s("POK", "Pokesdown"),
      s("BMH", "Bournemouth", true),
      s("BSM", "Branksome"),
      s("PKS", "Parkstone (Dorset)"),
      s("POO", "Poole", true),
      s("HAM", "Hamworthy"),
      s("WRM", "Wareham (Dorset)"),
      s("WOO", "Wool"),
      s("MTN", "Moreton (Dorset)"),
      s("DCH", "Dorchester South"),
      s("UPW", "Upwey"),
      s("WEY", "Weymouth"),
    ],
    branches: [
      { id: "windsor-reading", atCrs: "CLJ", label: "Windsor / Reading / Richmond", side: "down" },
      { id: "epsom", atCrs: "RAY", label: "Epsom / Dorking", side: "down" },
      { id: "chessington", atCrs: "RAY", label: "Chessington South", side: "down" },
      { id: "kingston-shepperton", atCrs: "NEM", label: "Kingston loop / Shepperton", side: "up" },
      { id: "hampton-court", atCrs: "SUR", label: "Hampton Court", side: "up" },
      { id: "guildford-cobham", atCrs: "SUR", label: "Guildford via Cobham", side: "down" },
      { id: "chertsey", atCrs: "WYB", label: "Chertsey / Staines", side: "up" },
      { id: "portsmouth-direct", atCrs: "WOK", label: "Portsmouth Direct", side: "down" },
      { id: "alton-ascot", atCrs: "BKO", label: "Alton line", side: "up" },
      { id: "west-of-england", atCrs: "BSK", label: "Salisbury / Exeter", side: "down" },
      { id: "reading-basingstoke", atCrs: "BSK", label: "Reading / Berks & Hants", side: "up" },
      { id: "fareham", atCrs: "ESL", label: "Portsmouth via Fareham", side: "down" },
      { id: "romsey-netley", atCrs: "ESL", label: "Romsey / Netley", side: "up" },
      { id: "lymington", atCrs: "BCU", label: "Lymington branch", side: "down" },
    ],
  },
  {
    id: "windsor-reading",
    title: "Windsor and Reading lines",
    shortTitle: "Windsor / Reading",
    parentId: "swml",
    parentAtCrs: "CLJ",
    stations: [
      s("CLJ", "Clapham Junction", true),
      s("WNT", "Wandsworth Town"),
      s("PUT", "Putney"),
      s("BNS", "Barnes", true),
      s("MTL", "Mortlake"),
      s("NSH", "North Sheen"),
      s("RMD", "Richmond (London)", true),
      s("SMG", "St Margarets (London)"),
      s("TWI", "Twickenham", true),
      s("WTN", "Whitton (London)"),
      s("FEL", "Feltham"),
      s("AFS", "Ashford (Surrey)"),
      s("SNS", "Staines", true),
      s("EGH", "Egham"),
      s("VIR", "Virginia Water", true),
      s("LNG", "Longcross"),
      s("SNG", "Sunningdale"),
      s("ACT", "Ascot (Berks)", true),
      s("MAO", "Martins Heron"),
      s("BCE", "Bracknell"),
      s("WKM", "Wokingham", true),
      s("WTI", "Winnersh Triangle"),
      s("WNS", "Winnersh"),
      s("EAR", "Earley"),
      s("RDG", "Reading", true),
    ],
    branches: [
      { id: "hounslow-loop", atCrs: "BNS", label: "Hounslow loop", side: "down" },
      { id: "shepperton", atCrs: "TWI", label: "Shepperton branch", side: "down" },
      { id: "windsor", atCrs: "SNS", label: "Windsor & Eton Riverside", side: "down" },
      { id: "chertsey", atCrs: "VIR", label: "Chertsey / Weybridge", side: "up" },
    ],
  },
  {
    id: "hounslow-loop",
    title: "Hounslow loop",
    shortTitle: "Hounslow loop",
    parentId: "windsor-reading",
    parentAtCrs: "BNS",
    stations: [
      s("BNS", "Barnes", true),
      s("BNI", "Barnes Bridge"),
      s("CHK", "Chiswick"),
      s("KWB", "Kew Bridge"),
      s("BFD", "Brentford"),
      s("SYL", "Syon Lane"),
      s("ISL", "Isleworth"),
      s("HOU", "Hounslow"),
      s("WTN", "Whitton (London)", true),
    ],
    branches: [],
  },
  {
    id: "shepperton",
    title: "Shepperton branch",
    shortTitle: "Shepperton",
    parentId: "windsor-reading",
    parentAtCrs: "TWI",
    stations: [
      s("TWI", "Twickenham", true),
      s("STW", "Strawberry Hill", true),
      s("FLW", "Fulwell"),
      s("HMP", "Hampton (London)"),
      s("KMP", "Kempton Park Racecourse"),
      s("SUU", "Sunbury"),
      s("UPH", "Upper Halliford"),
      s("SHP", "Shepperton"),
    ],
    branches: [],
  },
  {
    id: "windsor",
    title: "Windsor & Eton Riverside branch",
    shortTitle: "Windsor",
    parentId: "windsor-reading",
    parentAtCrs: "SNS",
    stations: [
      s("SNS", "Staines", true),
      s("WRY", "Wraysbury"),
      s("SNY", "Sunnymeads"),
      s("DAT", "Datchet"),
      s("WNR", "Windsor & Eton Riverside"),
    ],
    branches: [],
  },
  {
    id: "chertsey",
    title: "Chertsey and Staines branch",
    shortTitle: "Chertsey",
    parentId: "swml",
    parentAtCrs: "WYB",
    stations: [
      s("WYB", "Weybridge", true),
      s("ASN", "Addlestone"),
      s("CHY", "Chertsey"),
      s("VIR", "Virginia Water", true),
      s("SNS", "Staines", true),
    ],
    branches: [],
  },
  {
    id: "epsom",
    title: "Epsom and Dorking line",
    shortTitle: "Epsom",
    parentId: "swml",
    parentAtCrs: "RAY",
    stations: [
      s("RAY", "Raynes Park", true),
      s("MOT", "Motspur Park", true),
      s("SNL", "Stoneleigh"),
      s("EWW", "Ewell West"),
      s("EPS", "Epsom (Surrey)", true),
      s("AHD", "Ashtead"),
      s("LHD", "Leatherhead", true),
      s("BXW", "Box Hill & Westhumble"),
      s("DKG", "Dorking (Main)"),
      s("HLM", "Holmwood"),
      s("OLY", "Ockley"),
      s("BIG", "Billingshurst"),
    ],
    branches: [
      { id: "chessington", atCrs: "MOT", label: "Chessington branch", side: "down" },
    ],
  },
  {
    id: "chessington",
    title: "Chessington branch",
    shortTitle: "Chessington",
    parentId: "swml",
    parentAtCrs: "RAY",
    stations: [
      s("RAY", "Raynes Park", true),
      s("MOT", "Motspur Park", true),
      s("MAL", "Malden Manor"),
      s("TOL", "Tolworth"),
      s("CSN", "Chessington North"),
      s("CSS", "Chessington South"),
    ],
    branches: [],
  },
  {
    id: "kingston-shepperton",
    title: "Kingston loop and Shepperton line",
    shortTitle: "Kingston loop",
    parentId: "swml",
    parentAtCrs: "NEM",
    stations: [
      s("NEM", "New Malden", true),
      s("NBT", "Norbiton"),
      s("KNG", "Kingston"),
      s("HMW", "Hampton Wick"),
      s("TED", "Teddington"),
      s("STW", "Strawberry Hill", true),
      s("TWI", "Twickenham", true),
    ],
    branches: [
      { id: "shepperton", atCrs: "STW", label: "Shepperton branch", side: "down" },
    ],
  },
  {
    id: "hampton-court",
    title: "Hampton Court branch",
    shortTitle: "Hampton Court",
    parentId: "swml",
    parentAtCrs: "SUR",
    stations: [
      s("SUR", "Surbiton", true),
      s("THD", "Thames Ditton"),
      s("HMC", "Hampton Court"),
    ],
    branches: [],
  },
  {
    id: "guildford-cobham",
    title: "Guildford via Cobham line",
    shortTitle: "Cobham line",
    parentId: "swml",
    parentAtCrs: "SUR",
    stations: [
      s("SUR", "Surbiton", true),
      s("HYW", "Hinchley Wood"),
      s("CLG", "Claygate"),
      s("OXS", "Oxshott"),
      s("CSD", "Cobham & Stoke d'Abernon"),
      s("EFF", "Effingham Junction", true),
      s("HSY", "Horsley"),
      s("CLA", "Clandon"),
      s("LRD", "London Road (Guildford)"),
      s("GLD", "Guildford", true),
    ],
    branches: [],
  },
  {
    id: "portsmouth-direct",
    title: "Portsmouth Direct line",
    shortTitle: "Portsmouth Direct",
    parentId: "swml",
    parentAtCrs: "WOK",
    stations: [
      s("WOK", "Woking", true),
      s("WPL", "Worplesdon"),
      s("GLD", "Guildford", true),
      s("FNC", "Farncombe"),
      s("GOD", "Godalming"),
      s("MLF", "Milford (Surrey)"),
      s("WTY", "Witley"),
      s("HSL", "Haslemere", true),
      s("LIP", "Liphook"),
      s("LIS", "Liss"),
      s("PTR", "Petersfield"),
      s("RLN", "Rowlands Castle"),
      s("HAV", "Havant", true),
      s("BDH", "Bedhampton"),
      s("HLS", "Hilsea"),
      s("FTN", "Fratton", true),
      s("PMS", "Portsmouth & Southsea"),
      s("PMH", "Portsmouth Harbour"),
    ],
    branches: [],
  },
  {
    id: "alton-ascot",
    title: "Alton line",
    shortTitle: "Alton",
    parentId: "swml",
    parentAtCrs: "BKO",
    stations: [
      s("BKO", "Brookwood", true),
      s("AHV", "Ash Vale", true),
      s("AHT", "Aldershot", true),
      s("FNH", "Farnham"),
      s("BTY", "Bentley (Hampshire)"),
      s("AON", "Alton"),
    ],
    branches: [
      { id: "aldershot-guildford", atCrs: "AHV", label: "Ascot / Guildford", side: "up" },
    ],
  },
  {
    id: "aldershot-guildford",
    title: "Ascot to Guildford line",
    shortTitle: "Ascot / Guildford",
    parentId: "alton-ascot",
    parentAtCrs: "AHV",
    stations: [
      s("ACT", "Ascot (Berks)", true),
      s("BAG", "Bagshot"),
      s("CAM", "Camberley"),
      s("FML", "Frimley"),
      s("FNN", "Farnborough North"),
      s("NCM", "North Camp"),
      s("AHV", "Ash Vale", true),
      s("ASH", "Ash"),
      s("WAN", "Wanborough"),
      s("GLD", "Guildford", true),
    ],
    branches: [],
  },
  {
    id: "west-of-england",
    title: "West of England line",
    shortTitle: "West of England",
    parentId: "swml",
    parentAtCrs: "BSK",
    stations: [
      s("BSK", "Basingstoke", true),
      s("OVR", "Overton"),
      s("WCH", "Whitchurch (Hampshire)"),
      s("ADV", "Andover"),
      s("GRT", "Grateley"),
      s("SAL", "Salisbury", true),
      s("TIS", "Tisbury"),
      s("GIL", "Gillingham (Dorset)"),
      s("TMC", "Templecombe"),
      s("SHE", "Sherborne"),
      s("YVJ", "Yeovil Junction", true),
      s("CKN", "Crewkerne"),
      s("AXM", "Axminster"),
      s("HON", "Honiton"),
      s("FNT", "Feniton"),
      s("WHM", "Whimple"),
      s("CBK", "Cranbrook (Devon)"),
      s("PIN", "Pinhoe"),
      s("EXC", "Exeter Central", true),
      s("EXD", "Exeter St David's", true),
    ],
    branches: [],
  },
  {
    id: "reading-basingstoke",
    title: "Reading and Berks & Hants lines",
    shortTitle: "Reading line",
    parentId: "swml",
    parentAtCrs: "BSK",
    stations: [
      s("BSK", "Basingstoke", true),
      s("BMY", "Bramley (Hampshire)"),
      s("MOR", "Mortimer"),
      s("RDG", "Reading", true),
    ],
    branches: [],
  },
  {
    id: "fareham",
    title: "Portsmouth via Fareham line",
    shortTitle: "Fareham line",
    parentId: "swml",
    parentAtCrs: "ESL",
    stations: [
      s("ESL", "Eastleigh", true),
      s("HDE", "Hedge End"),
      s("BOE", "Botley"),
      s("FRM", "Fareham", true),
      s("PTC", "Portchester"),
      s("CSA", "Cosham", true),
      s("HLS", "Hilsea"),
      s("FTN", "Fratton", true),
      s("PMS", "Portsmouth & Southsea"),
      s("PMH", "Portsmouth Harbour"),
    ],
    branches: [],
  },
  {
    id: "romsey-netley",
    title: "Romsey and Netley lines",
    shortTitle: "Romsey / Netley",
    parentId: "swml",
    parentAtCrs: "ESL",
    stations: [
      s("ESL", "Eastleigh", true),
      s("CFR", "Chandlers Ford"),
      s("ROM", "Romsey", true),
      s("DBG", "Mottisfont & Dunbridge"),
      s("DEN", "Dean (Wilts)"),
      s("SAL", "Salisbury", true),
    ],
    branches: [],
  },
  {
    id: "lymington",
    title: "Lymington branch",
    shortTitle: "Lymington",
    parentId: "swml",
    parentAtCrs: "BCU",
    stations: [
      s("BCU", "Brockenhurst", true),
      s("LYT", "Lymington Town"),
      s("LYP", "Lymington Pier"),
    ],
    branches: [],
  },
];

export const SIGNALLING_CORRIDORS: Record<SignallingCorridorId, SignallingCorridor> =
  Object.fromEntries(CORRIDORS.map((c) => [c.id, c]));

/** Every corridor id, for route generation and tests. */
export const SIGNALLING_CORRIDOR_IDS = Object.keys(SIGNALLING_CORRIDORS);

export function namedSignallingCorridor(value: string | undefined): SignallingCorridor | undefined {
  if (!value) return undefined;
  return SIGNALLING_CORRIDORS[value.toLowerCase()];
}

/** Ordered CRS codes — the shape `resolveAreasForCorridor` and the renderer want. */
export function corridorStationCrs(corridor: SignallingCorridor): string[] {
  return corridor.stations.map((s) => s.crs);
}

/**
 * The corridor to offer on a station board.
 *
 * A station can sit on several corridors (Guildford is on three). The trunk
 * wins, so a Waterloo-bound passenger gets the main line rather than whichever
 * branch happens to be declared first.
 */
export function stationSignallingCorridor(crs: string): SignallingCorridor | undefined {
  const normalized = crs.toUpperCase();
  const onCorridor = Object.values(SIGNALLING_CORRIDORS).filter((corridor) =>
    corridor.stations.some((s) => s.crs === normalized),
  );
  return onCorridor.find((c) => !c.parentId) ?? onCorridor[0];
}
