import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  SIGNALLING_CORRIDORS,
  SIGNALLING_CORRIDOR_IDS,
  corridorStationCrs,
  namedSignallingCorridor,
  stationSignallingCorridor,
  trackRoleName,
} from "./signalling-corridors";

/**
 * Guardrail for hand-authored corridor data.
 *
 * The station lists were generated by looking each name up in the GTFS stops
 * file rather than typed from memory, because a first pass written from memory
 * had 72 of 222 codes wrong — including Chessington North and South, whose
 * codes were transposed. These tests re-check every code against the same GTFS
 * data so a later hand-edit cannot quietly reintroduce that.
 *
 * GTFS is the timetable the routing engine itself runs on, so a code that fails
 * here is a code no journey could ever be planned to.
 */
const gtfsStops = (() => {
  // stops.txt inside data/gtfs/gb-rail.gtfs.zip, extracted to a fixture so the
  // test does not need to unzip 15MB on every run.
  const raw = readFileSync(new URL("./__fixtures__/gtfs-crs.json", import.meta.url), "utf8");
  return JSON.parse(raw) as Record<string, string>;
})();

const corridors = Object.values(SIGNALLING_CORRIDORS);

describe("corridor station data", () => {
  it("has the SWML trunk plus its branches", () => {
    expect(SIGNALLING_CORRIDOR_IDS).toContain("swml");
    expect(corridors.length).toBeGreaterThan(10);
  });

  it("uses only CRS codes that exist in the national timetable", () => {
    const unknown: string[] = [];
    for (const corridor of corridors) {
      for (const station of corridor.stations) {
        if (!gtfsStops[station.crs]) unknown.push(`${corridor.id}/${station.crs}`);
      }
    }
    expect(unknown).toEqual([]);
  });

  it("names each station the way the timetable names it", () => {
    const mismatched: string[] = [];
    const normalise = (v: string) => v.toLowerCase().replace(/[^a-z0-9]/g, "");
    for (const corridor of corridors) {
      for (const station of corridor.stations) {
        const real = gtfsStops[station.crs];
        if (real && normalise(real) !== normalise(station.name)) {
          mismatched.push(`${station.crs}: "${station.name}" vs "${real}"`);
        }
      }
    }
    expect(mismatched).toEqual([]);
  });

  it("never repeats a station within one corridor", () => {
    for (const corridor of corridors) {
      const crs = corridorStationCrs(corridor);
      expect(new Set(crs).size, `${corridor.id} repeats a station`).toBe(crs.length);
    }
  });

  it("gives every corridor at least two stations", () => {
    for (const corridor of corridors) {
      expect(corridor.stations.length, corridor.id).toBeGreaterThanOrEqual(2);
    }
  });
});

describe("branches", () => {
  it("points every branch at a corridor that exists", () => {
    const dangling: string[] = [];
    for (const corridor of corridors) {
      for (const branch of corridor.branches) {
        if (!SIGNALLING_CORRIDORS[branch.id]) dangling.push(`${corridor.id} -> ${branch.id}`);
      }
    }
    // The old code had 14 branch links against 15 branch pages, kept in sync by
    // hand in two separate files.
    expect(dangling).toEqual([]);
  });

  it("leaves from a station that is actually on the parent corridor", () => {
    const bad: string[] = [];
    for (const corridor of corridors) {
      const onCorridor = new Set(corridorStationCrs(corridor));
      for (const branch of corridor.branches) {
        if (!onCorridor.has(branch.atCrs)) bad.push(`${corridor.id}: ${branch.id} at ${branch.atCrs}`);
      }
    }
    expect(bad).toEqual([]);
  });

  it("shares the junction station with the corridor it branches to", () => {
    const bad: string[] = [];
    for (const corridor of corridors) {
      for (const branch of corridor.branches) {
        const target = SIGNALLING_CORRIDORS[branch.id];
        if (!target) continue;
        if (!corridorStationCrs(target).includes(branch.atCrs)) {
          bad.push(`${branch.id} does not include its junction ${branch.atCrs}`);
        }
      }
    }
    expect(bad).toEqual([]);
  });

  it("gives each child a parent that lists it", () => {
    for (const corridor of corridors) {
      if (!corridor.parentId) continue;
      const parent = SIGNALLING_CORRIDORS[corridor.parentId];
      expect(parent, `${corridor.id} has an unknown parent`).toBeDefined();
      expect(corridorStationCrs(parent!)).toContain(corridor.parentAtCrs!);
    }
  });
});

describe("lookups", () => {
  it("finds a corridor case-insensitively", () => {
    expect(namedSignallingCorridor("SWML")?.id).toBe("swml");
    expect(namedSignallingCorridor("swml")?.id).toBe("swml");
    expect(namedSignallingCorridor("nope")).toBeUndefined();
    expect(namedSignallingCorridor(undefined)).toBeUndefined();
  });

  it("offers the trunk, not a branch, for a station on both", () => {
    // Weybridge is on the SWML and on the Chertsey branch; a passenger at
    // Weybridge wants the main line.
    expect(stationSignallingCorridor("WYB")?.id).toBe("swml");
    expect(stationSignallingCorridor("wyb")?.id).toBe("swml");
    // Guildford is only on branches, so it gets one of those.
    expect(stationSignallingCorridor("GLD")).toBeDefined();
    expect(stationSignallingCorridor("ZZZ")).toBeUndefined();
  });
});

describe("track role names", () => {
  it("names the lines it knows", () => {
    expect(trackRoleName("1100")).toBe("Down Fast");
    expect(trackRoleName("2200")).toBe("Up Slow");
  });

  it("says the raw id rather than guessing at one it does not know", () => {
    // Track Model has no name field for a running line, so an unmapped id must
    // not be given an invented label.
    expect(trackRoleName("4321")).toBe("Line 4321");
  });
});
